#!/usr/bin/env node

/**
 * Auto-generates src/components/index.tsx by scanning the components directory.
 * This eliminates the need to manually maintain barrel exports.
 * 
 * Runs automatically before build via the "prebuild" npm script.
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const COMPONENTS_DIR = path.resolve(__dirname, "../src/components");
const OUTPUT_FILE = path.resolve(COMPONENTS_DIR, "index.tsx");

// Files/folders to ignore
const IGNORE = new Set([
  "index.tsx",
  "index.ts",
  ".DS_Store",
  "node_modules",
]);

function generateExports() {
  console.log("🔍 Scanning components directory...");

  const entries = fs.readdirSync(COMPONENTS_DIR, { withFileTypes: true });

  const componentFolders = entries
    .filter((entry) => {
      // Only include directories that aren't in the ignore list
      return entry.isDirectory() && !IGNORE.has(entry.name);
    })
    .map((entry) => entry.name)
    .sort(); // Alphabetical order

  console.log(`✅ Found ${componentFolders.length} components:`, componentFolders);

  // Generate export statements
  const exports = componentFolders
    .map((folder) => {
      // Check if the main component file exists
      const componentFile = path.join(COMPONENTS_DIR, folder, `${folder}.tsx`);
      if (!fs.existsSync(componentFile)) {
        console.warn(`⚠️  Skipping ${folder}: ${folder}.tsx not found`);
        return null;
      }
      return `export * from "./${folder}/${folder}";`;
    })
    .filter(Boolean); // Remove null entries

  // Create file content with header
  const content = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * This file is automatically generated by scripts/generate-exports.js
 * Run 'npm run generate:exports' to regenerate.
 * 
 * Last generated: ${new Date().toISOString()}
 */

${exports.join("\n")}
`;

  // Write the file
  fs.writeFileSync(OUTPUT_FILE, content, "utf8");
  
  console.log(`✨ Generated ${OUTPUT_FILE}`);
  console.log(`📦 Exported ${exports.length} components`);
}

try {
  generateExports();
} catch (error) {
  console.error("❌ Error generating exports:", error);
  process.exit(1);
}

