#!/usr/bin/env node

/**
 * Auto-generates src/components/index.tsx by scanning the components directory.
 * This eliminates the need to manually maintain barrel exports.
 *
 * Usage:
 *  - Automatic: Runs before every build via "prebuild" npm script
 *  - Manual: npm run generate:exports
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const COMPONENTS_DIR = path.resolve(__dirname, "../src/components");
const OUTPUT_FILE = path.resolve(COMPONENTS_DIR, "index.tsx");

// Files/folders to ignore
const IGNORE = new Set(["index.tsx", "index.ts", ".DS_Store", "node_modules"]);

/**
 * Recursively find all component files following the pattern:
 * {folder-name}/{folder-name}.tsx at any nesting level
 */
function findComponents(dir, baseDir = dir) {
  const components = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    // Skip ignored files/folders
    if (IGNORE.has(entry.name)) continue;

    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      // Check if this directory contains a matching component file
      const componentFile = path.join(fullPath, `${entry.name}.tsx`);

      if (fs.existsSync(componentFile)) {
        // Calculate relative path from components dir
        const relativePath = path.relative(baseDir, fullPath);
        components.push({
          name: entry.name,
          path: relativePath,
        });
      }

      // Recursively scan subdirectories
      components.push(...findComponents(fullPath, baseDir));
    }
  }

  return components;
}

function generateExports() {
  console.log("🔍 Scanning components directory recursively...");

  const components = findComponents(COMPONENTS_DIR);

  // Sort by name for consistent output
  components.sort((a, b) => a.name.localeCompare(b.name));

  console.log(
    `✅ Found ${components.length} components:`,
    components.map((c) => c.name)
  );

  // Generate export statements
  const exports = components.map((component) => {
    // Use forward slashes for imports (works on all platforms)
    const importPath = component.path.split(path.sep).join("/");
    return `export * from "./${importPath}/${component.name}";`;
  });

  // Create file content with header
  // Note: "use client" is required because these components use tailwind-variants
  // which may use React context internally
  const content = `"use client";

/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated by scripts/generate-exports.mjs
 * Run 'npm run generate:exports' to regenerate.
 *
 * Last generated: ${new Date().toISOString()}
 */

${exports.join("\n")}
`;

  // Write the file
  fs.writeFileSync(OUTPUT_FILE, content, "utf8");

  console.log(`✨ Generated ${OUTPUT_FILE}`);
  console.log(`📦 Exported ${exports.length} components`);
}

try {
  generateExports();
} catch (error) {
  console.error("❌ Error generating exports:", error);
  process.exit(1);
}
